version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: smer
      PGDATA: /data/postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    volumes:
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
      - ./cmd:/app/cmd
      - ./migrations:/migrations
      - ./internal:/app/internal
      - ./pkg:/app/pkg
      - ./.env:/.env
    env_file:
      ./.env
    depends_on:
      - postgres
    restart: unless-stopped
  frontend:
    container_name: frontend
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: always
    env_file:
      ./.env
    ports:
      - "3000:3000"
volumes:
  postgres:
